#!/usr/bin/env python3
"""Generate source PNG frames and LVGL RGB565 C assets for AI-Code-Pager."""

from __future__ import annotations

from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
PNG_ROOT = ROOT / "assets" / "pet"
C_FILE = ROOT / "src" / "assets" / "pet_animations.c"
PREVIEW = ROOT / "assets" / "pet" / "preview.png"

LOGICAL = 40
SCALE = 2
SIZE = LOGICAL * SCALE
BG = (21, 33, 28, 255)
INK = (18, 25, 20, 255)
GREEN_DARK = (44, 101, 63, 255)
GREEN = (87, 174, 91, 255)
GREEN_LIGHT = (157, 218, 116, 255)
CREAM = (232, 221, 168, 255)
PINK = (232, 126, 117, 255)
YELLOW = (239, 202, 95, 255)


def px(draw: ImageDraw.ImageDraw, box, fill):
    draw.rectangle(box, fill=fill)


def dragon_base(frame: int, pose: str) -> Image.Image:
    im = Image.new("RGBA", (LOGICAL, LOGICAL), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    bob = [0, -1, 0, 1][frame]

    # Tail, body, belly and feet.
    d.polygon([(8, 27+bob), (3, 24+bob), (5, 30+bob), (11, 32+bob)], fill=GREEN_DARK)
    px(d, (10, 18+bob, 29, 33+bob), GREEN_DARK)
    px(d, (12, 17+bob, 27, 32+bob), GREEN)
    px(d, (17, 23+bob, 25, 32+bob), CREAM)
    px(d, (10, 32+bob, 17, 35+bob), GREEN_DARK)
    px(d, (24, 32+bob, 31, 35+bob), GREEN_DARK)

    # Head, snout, ears/horns.
    px(d, (9, 7+bob, 29, 22+bob), GREEN_DARK)
    px(d, (11, 6+bob, 27, 21+bob), GREEN)
    d.polygon([(12, 7+bob), (10, 2+bob), (16, 6+bob)], fill=GREEN_LIGHT)
    d.polygon([(24, 6+bob), (29, 2+bob), (28, 9+bob)], fill=GREEN_LIGHT)
    px(d, (17, 15+bob, 31, 22+bob), GREEN_LIGHT)
    px(d, (29, 17+bob, 32, 20+bob), GREEN_LIGHT)
    px(d, (15, 11+bob, 17, 13+bob), INK)
    px(d, (24, 11+bob, 26, 13+bob), INK)
    px(d, (28, 17+bob, 29, 18+bob), INK)
    px(d, (20, 20+bob, 27, 21+bob), INK)

    if pose == "scratch":
        hand_y = [8, 6, 7, 10][frame] + bob
        px(d, (7, 16+bob, 11, 25+bob), GREEN_DARK)
        px(d, (5, hand_y, 10, hand_y+4), GREEN_LIGHT)
        px(d, (5, hand_y+3, 7, 18+bob), GREEN)
        if frame in (1, 2):
            px(d, (3, 4, 4, 7), YELLOW)
            px(d, (6, 2, 7, 5), YELLOW)
    elif pose == "point_down":
        x = [29, 30, 30, 29][frame]
        px(d, (x-1, 22+bob, x+3, 31), GREEN)
        px(d, (x+1, 29, x+5, 33), GREEN_LIGHT)
        px(d, (x+4, 32, x+5, 36), GREEN_LIGHT)
        px(d, (33, 36, 36, 37), YELLOW)
        px(d, (34, 37, 35, 38), YELLOW)
    elif pose == "cheer":
        lift = [2, 0, 1, 3][frame]
        px(d, (6, 10-lift+bob, 11, 20+bob), GREEN)
        px(d, (4, 7-lift+bob, 8, 12-lift+bob), GREEN_LIGHT)
        px(d, (28, 9-lift+bob, 33, 20+bob), GREEN)
        px(d, (32, 6-lift+bob, 36, 11-lift+bob), GREEN_LIGHT)
        px(d, (19, 18+bob, 27, 21+bob), PINK)
        for x, y, color in [(3, 3, PINK), (19, 2, YELLOW), (36, 3, CREAM)]:
            if (x + frame) % 2:
                px(d, (x, y+frame%2, x+1, y+2+frame%2), color)
    elif pose == "sleep":
        # Replace standing silhouette with a low curled posture.
        im = Image.new("RGBA", (LOGICAL, LOGICAL), (0, 0, 0, 0))
        d = ImageDraw.Draw(im)
        y = [1, 1, 0, 0][frame]
        px(d, (6, 23+y, 32, 34+y), GREEN_DARK)
        px(d, (9, 21+y, 29, 32+y), GREEN)
        d.polygon([(8, 29+y), (2, 31+y), (8, 34+y)], fill=GREEN_DARK)
        px(d, (22, 17+y, 35, 29+y), GREEN)
        px(d, (28, 25+y, 37, 30+y), GREEN_LIGHT)
        px(d, (25, 21+y, 28, 22+y), INK)
        px(d, (31, 21+y, 34, 22+y), INK)
        px(d, (31, 28+y, 35, 29+y), INK)
        px(d, (11, 31+y, 20, 34+y), CREAM)
        # Rhythmic sleep bubble and Z marks.
        bubble = [1, 2, 3, 2][frame]
        d.ellipse((36-bubble, 23-bubble, 36+bubble, 23+bubble), fill=CREAM, outline=INK)
        px(d, (29, 10, 34, 11), YELLOW)
        px(d, (33, 11, 34, 13), YELLOW)
        px(d, (29, 13, 34, 14), YELLOW)
        if frame >= 2:
            px(d, (35, 5, 39, 6), YELLOW)
            px(d, (38, 6, 39, 8), YELLOW)
            px(d, (35, 8, 39, 9), YELLOW)

    return im.resize((SIZE, SIZE), Image.Resampling.NEAREST)


def rgb565_bytes(im: Image.Image) -> bytes:
    canvas = Image.new("RGBA", im.size, BG)
    canvas.alpha_composite(im)
    out = bytearray()
    pixels = (canvas.get_flattened_data() if hasattr(canvas, "get_flattened_data")
              else canvas.getdata())
    for r, g, b, _ in pixels:
        value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        # Native little-endian lv_color16_t. Display byte swapping is handled
        # by the Zephyr ST7789 driver.
        out.extend((value & 0xFF, value >> 8))
    return bytes(out)


def emit_c(frames: dict[str, list[Image.Image]]) -> None:
    lines = [
        "/* Generated by tools/generate_pet_assets.py. Do not edit. */",
        '#include "pet_animations.h"',
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "#ifndef LV_ATTRIBUTE_LARGE_CONST",
        "#define LV_ATTRIBUTE_LARGE_CONST",
        "#endif",
        "",
    ]
    for action, action_frames in frames.items():
        for index, frame in enumerate(action_frames):
            symbol = f"pet_{action}_{index}"
            data = rgb565_bytes(frame)
            lines.append(
                f"static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST "
                f"uint8_t {symbol}_map[] = {{"
            )
            for pos in range(0, len(data), 24):
                chunk = ", ".join(f"0x{x:02x}" for x in data[pos:pos+24])
                lines.append(f"    {chunk},")
            lines += [
                "};",
                f"const lv_img_dsc_t {symbol} = {{",
                "    .header.cf = LV_IMG_CF_TRUE_COLOR,",
                "    .header.always_zero = 0,",
                "    .header.reserved = 0,",
                f"    .header.w = {SIZE},",
                f"    .header.h = {SIZE},",
                f"    .data_size = {len(data)},",
                f"    .data = {symbol}_map,",
                "};",
                "",
            ]
    C_FILE.parent.mkdir(parents=True, exist_ok=True)
    C_FILE.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    actions = ("scratch", "point_down", "cheer", "sleep")
    frames: dict[str, list[Image.Image]] = {}
    for action in actions:
        target = PNG_ROOT / action
        target.mkdir(parents=True, exist_ok=True)
        frames[action] = []
        for index in range(4):
            frame = dragon_base(index, action)
            frame.save(target / f"{index:02d}.png")
            frames[action].append(frame)

    preview = Image.new("RGBA", (SIZE * 4, SIZE * 4), BG)
    for row, action in enumerate(actions):
        for col, frame in enumerate(frames[action]):
            preview.alpha_composite(frame, (col * SIZE, row * SIZE))
    preview.convert("RGB").save(PREVIEW)
    emit_c(frames)
    print(f"generated 16 PNG frames, {PREVIEW}, and {C_FILE}")


if __name__ == "__main__":
    main()
